run:
  profile: write-heavy
  client: awscli
  endpoint: "http://192.168.20.38:9080"
  # endpoints:
  #   - "http://192.168.20.35:9080"
  #   - "http://192.168.20.38:9080"
  bucket: cluster_test
  access_key: "fMIwNE-6kamj3s9LSADxhfJL"
  secret_key: "TSDFYQYucGxDEC0F5c4x_1QtlzLBsCkzkubA_WF_"
  threads: 2
  data_dir: "./loadset/data"
  report: "test-real-report.json"
  metrics: "test-real-metrics.csv"
